#goal
project11_nav_msgs/TaskInformation[] tasks
---
#result
project11_nav_msgs/TaskInformation[] tasks

# Error codes (copied from nav2_msgs)
# Note: The expected priority order of the errors should match the message order
uint16 NONE=0
uint16 UNKNOWN=9000
uint16 FAILED_TO_LOAD_BEHAVIOR_TREE=9001
uint16 TF_ERROR=9002
uint16 TIMEOUT=9003

uint16 error_code
string error_msg
---
# feedback
project11_nav_msgs/TaskFeedback feedback
